import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { PunHeader } from "./_core/header-bar";
import ConfigProvider from "antd/es/config-provider";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const montserrat = Montserrat({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Pun fashion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
      <ConfigProvider theme={{ hashed: false }}>
        <PunHeader />
        <AntdRegistry>
          <main className="container mx-auto">{children}</main>
        </AntdRegistry>
      </ConfigProvider>
      </body>
    </html>
  );
}
