import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { PunHeader } from "./_core/header-bar";

const montserrat = Montserrat({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Pun fashion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <PunHeader />
        {children}
      </body>
    </html>
  );
}
